# Generated by Django 4.1.1 on 2022-10-17 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Features',
            fields=[
                ('FeatureId', models.AutoField(primary_key=True, serialize=False)),
                ('FeatureName', models.CharField(max_length=10)),
                ('FeaturePriority', models.IntegerField(default=0)),
                ('FeatureSprint', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Sprints',
            fields=[
                ('SprintId', models.AutoField(primary_key=True, serialize=False)),
                ('SprintName', models.CharField(max_length=10)),
                ('SprintDuration', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Taches',
            fields=[
                ('TacheId', models.AutoField(primary_key=True, serialize=False)),
                ('TacheName', models.CharField(max_length=10)),
                ('TacheStoryPoint', models.IntegerField()),
                ('TacheProgress', models.IntegerField(default=0)),
                ('TacheFeature', models.IntegerField(default=0)),
            ],
        ),
    ]
