# Generated by Django 4.1.1 on 2022-10-20 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SprintApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='features',
            name='FeatureSprint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SprintApp.sprints'),
        ),
    ]
