# Generated by Django 4.1.1 on 2022-10-20 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SprintApp', '0002_alter_features_featuresprint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taches',
            name='TacheFeature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SprintApp.features'),
        ),
    ]
